# Run sphinx's linkcheck to pop up
# broken and redirected links.

name: Linkcheck

on:
  push:
    paths:
      - '*.diff'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['main', '3.13', '3.12']
        include:
          - branch: 'main'
            fix-broken: 'fix-broken.diff'
            #fix-redir-with-found: 'fix-redir-with-found.diff'
          - branch: '3.13'
            fix-broken: 'fix-broken.diff'
          - branch: '3.12'
            fix-broken: 'fix-broken-3.12.diff'
            #fix-redir-with-found: 'fix-redir-with-found.diff'
      fail-fast: false
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check out CPython
        uses: actions/checkout@v4
        with:
          repository: python/cpython
          persist-credentials: false
          ref: ${{ matrix.branch }}
          path: cpython

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3'
          cache: 'pip'
          cache-dependency-path: 'cpython/Doc/requirements.txt'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install flake8

      - name: Apply fix-broken
        if: matrix.fix-broken != 0
        run: |
          cd cpython
          cat ../${{ matrix.fix-broken }}
          git apply ../${{ matrix.fix-broken }}

      - name: Apply fix-redir-with-found
        if: matrix.fix-redir-with-found != 0
        run: |
          cd cpython
          cat ../${{ matrix.fix-redir-with-found }}
          git apply ../${{ matrix.fix-redir-with-found }}

      # Exclude other reported issues, to get e.g. W605 invalid escape sequence '\d'
      - name: Flake8 on Doc/conf.py
        run: |
          flake8 cpython/Doc/conf.py --ignore E122,E501,E401,E402,F401,W291 --output-file ${{ matrix.branch }}-flake8.txt
      
      - name: Make virtual environment
        run: |
          make -C cpython/Doc venv

      - name: Build documentation
        run: |
          make -C cpython/Doc html
      
      - name: Run linkcheck
        run: |
          make -C cpython/Doc linkcheck SPHINXOPTS="--keep-going" SPHINXERRORHANDLING="" || true

      - name: Split log
        run: |
          BRANCH=${{ matrix.branch }}
          SRCFILE="cpython/Doc/build/linkcheck/output.txt"
          touch ${BRANCH}-log-broken.txt ${BRANCH}-log-redir-permanently.txt ${BRANCH}-log-redir-with-found.txt          
          grep ' \[broken] ' ${SRCFILE} | sort > ${BRANCH}-log-broken.txt || true
          grep ' \[redirected temporarily] ' | sort > ${BRANCH}-log-redir-temporarily.txt || true
          grep ' \[redirected permanently] ' ${SRCFILE} | sort > ${BRANCH}-log-redir-permanently.txt || true
          grep ' \[redirected with Found] ' ${SRCFILE} | sort > ${BRANCH}-log-redir-with-found.txt || true
          sed '/\[broken]/d;/\[redirected temporarily]/d;/\[redirected with Found]/d;/\[redirected permanently]/d' ${SRCFILE} | sort > ${BRANCH}-log-others.txt
          sort ${SRCFILE} > ${BRANCH}-linkcheck.txt

      - run: cat ${{ matrix.branch }}-log-broken.txt
      - run: cat ${{ matrix.branch }}-log-redir-permanently.txt
      - run: cat ${{ matrix.branch }}-log-redir-with-found.txt
      - run: cat ${{ matrix.branch }}-log-others.txt

      - name: Upload output as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.branch }}-logs
          path: |
            ${{ matrix.branch }}-*.txt
            ${{ matrix.branch }}-flake8.txt

  push:
    runs-on: ubuntu-latest
    needs: linkcheck
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      
      - name: Download logs
        uses: actions/download-artifact@v4
        
      - name: Commit and push logs
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git status
          git add *-logs/*.txt
          git diff-index --cached --quiet HEAD || { git commit -m "Update linkcheck log"; git pull --rebase; git push; }
