# Run sphinx's linkcheck to pop up
# broken and redirected links.

name: Linkcheck

on:
  push:
    paths:
      - '*.diff'
  workflow_dispatch:
    inputs:
      patchfile:
        type: choice
        description: Patch to apply
        default: all
        options:
        - 'fix-broken-links'
        - 'fix-most-redirects'
        - 'all'
      SPHINXOPTS:
        description: 'Sphinx options'
        required: false
        type: string

permissions:
  contents: write

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Check out CPython
        uses: actions/checkout@v3
        with:
          repository: python/cpython
          persist-credentials: false
          path: cpython

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'cpython/Doc/requirements.txt'

      - name: Apply fix-broken-links patch
        if:  inputs.patchfile == "fix-broken-links" || inputs.patchfile == 'all' 
        run: |
          cd cpython
          cat ../fix-broken-links.diff
          git apply ../fix-broken-links.diff

      - name: Apply fix-most-redirects patch
        if:  inputs.patchfile == "fix-most-redirects" || inputs.patchfile == 'all' 
        run: |
          cd cpython
          cat ../fix-most-redirects.diff
          git apply ../fix-most-redirects.diff

      - name: Make virtual environment
        run: |
          make -C cpython/Doc venv

      - name: Run linkcheck
        run: |
          make -C cpython/Doc linkcheck SPHINXOPTS="--keep-going ${{ github.event.inputs.SPHINXOPTS }}" || true

      - name: Split log
        run: |
          touch log-broken.txt log-redir-permanently.txt log-redir-with-found.txt
          srcfile="cpython/Doc/build/linkcheck/output.txt "
          grep ' \[broken] ' ${srcfile} > log-broken.txt || true
          grep ' \[redirected permanently] ' ${srcfile} > log-redir-permanently.txt || true
          grep ' \[redirected with Found] ' ${srcfile} > log-redir-with-found.txt || true
          sed '/\[broken]/d;/\[redirected with Found]/d;/\[redirected permanently]/d' ${srcfile} > log-others.txt
          cp ${srcfile} linkcheck.txt

      - run: cat log-broken.txt
      - run: cat log-redir-permanently.txt
      - run: cat log-redir-with-found.txt
      - run: cat log-others.txt

      - name: Commit and push logs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add *.txt
          git commit --allow-empty -m "Update linkcheck log" -m "SPHINXOPTS used: '--keep-going ${{ github.event.inputs.SPHINXOPTS }}'"
          git push

      - name: Upload output as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: linkcheck-output
          path: cpython/Doc/build/linkcheck/output.txt
