# Run sphinx's linkcheck to pop up
# broken and redirected links.

name: Linkcheck

on:
  push:
    paths:
      - '*.diff'
  workflow_dispatch:
    inputs:
      SPHINXOPTS:
        description: 'Sphinx options'
        required: false
        type: string

permissions:
  contents: write

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Check out CPython
        uses: actions/checkout@v3
        with:
          repository: python/cpython
          persist-credentials: false
          path: cpython

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'cpython/Doc/requirements.txt'

      - name: Apply fix-broken-links patch
        run: |
          cd cpython
          git apply ../fix-broken-links.diff

      - name: Make virtual environment
        run: |
          make -C cpython/Doc venv

      - name: Run linkcheck
        run: |
          make -C cpython/Doc linkcheck SPHINXOPTS="--keep-going ${{ github.event.inputs.SPHINXOPTS }}" || true

      - name: Store log
        run: |
          cp \
            cpython/Doc/build/linkcheck/output.txt \
            linkcheck.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add linkcheck.txt
          git commit --allow-empty -m "Update linkcheck log" -m "SPHINXOPTS used: '--keep-going ${{ github.event.inputs.SPHINXOPTS }}'"
          git push

      - name: Upload output as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: linkcheck-output
          path: cpython/Doc/build/linkcheck/output.txt
