# Run sphinx's linkcheck to pop up
# broken and redirected links.

name: Linkcheck

on:
  push:
    paths:
      - '*.diff'
  workflow_dispatch:
    inputs:
      SPHINXOPTS:
        description: 'Sphinx options'
        required: false
        type: string

permissions:
  contents: write

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['main', '3.11', '3.10', '3.9', '3.8', '3.7']
        include:
          - branch: 'main'
            fix-most-redirects: 'fix-most-redirects.diff'
            fix-broken-links: 'fix-broken-links.diff'
          - branch: '3.11'
            fix-most-redirects: 'fix-most-redirects.diff'
            fix-broken-links: 'fix-broken-links-311.diff'
          - branch: '3.10'
            fix-most-redirects: 'fix-most-redirects-310.diff'
            fix-broken-links: 'fix-broken-links-311.diff'
          - branch: '3.9'
            fix-most-redirects: 'fix-most-redirects-310.diff'
            fix-broken-links: 'fix-broken-links-311.diff'
          - branch: '3.8'
            fix-most-redirects: 'fix-most-redirects-310.diff'
            fix-broken-links: 'fix-broken-links-311.diff'
          - branch: '3.7'
            fix-most-redirects: 'fix-most-redirects-310.diff'
            fix-broken-links: 'fix-broken-links-311.diff'
      fail-fast: false
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Check out CPython
        uses: actions/checkout@v3
        with:
          repository: python/cpython
          persist-credentials: false
          ref: ${{ matrix.branch }}
          path: cpython

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'cpython/Doc/requirements.txt'

      - name: Apply fix-most-redirects patch
        run: |
          cd cpython
          cat ../${{ matrix.fix-most-redirects }}
          git apply ../${{ matrix.fix-most-redirects }}

      - name: Apply fix-broken-links patch
        run: |
          cd cpython
          cat ../${{ matrix.fix-broken-links }}
          git apply ../${{ matrix.fix-broken-links }}

      - name: Make virtual environment
        run: |
          make -C cpython/Doc venv

      - name: Run linkcheck
        run: |
          make -C cpython/Doc linkcheck SPHINXOPTS="--keep-going ${{ github.event.inputs.SPHINXOPTS }}" || true

      - name: Split log
        run: |
          BRANCH=${{ matrix.branch }}
          SRCFILE="cpython/Doc/build/linkcheck/output.txt "
          touch ${BRANCH}-log-broken.txt ${BRANCH}-log-redir-permanently.txt ${BRANCH}-log-redir-with-found.txt          
          grep ' \[broken] ' ${SRCFILE} > ${BRANCH}-log-broken.txt || true
          grep ' \[redirected permanently] ' ${SRCFILE} > ${BRANCH}-log-redir-permanently.txt || true
          grep ' \[redirected with Found] ' ${SRCFILE} > ${BRANCH}-log-redir-with-found.txt || true
          sed '/\[broken]/d;/\[redirected with Found]/d;/\[redirected permanently]/d' ${SRCFILE} > ${BRANCH}-log-others.txt
          cp ${SRCFILE} ${BRANCH}-linkcheck.txt

      - run: cat ${{ matrix.branch }}-log-broken.txt
      - run: cat ${{ matrix.branch }}-log-redir-permanently.txt
      - run: cat ${{ matrix.branch }}-log-redir-with-found.txt
      - run: cat ${{ matrix.branch }}-log-others.txt

      - name: Commit and push logs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add *.txt
          git commit --allow-empty -m "Update linkcheck log" -m "SPHINXOPTS used: '--keep-going ${{ github.event.inputs.SPHINXOPTS }}'"
          git push

      - name: Upload output as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.branch }}-linkcheck-output
          path: cpython/Doc/build/linkcheck/output.txt
